FROM ubuntu
RUN sudo apt-get update
RUN sudo apt-get -y install software-properties-common
RUN sudo add-apt-repository -y ppa:brightbox/ruby-ng
RUN sudo apt-get update
RUN sudo apt-get -y install ruby2.1
